global:
  grafana:
    enabled: false
    proxy: false
kubecostProductConfigs:
  athenaBucketName: ${athenaBucketName}
  athenaDatabase: ${athenaDatabase}
  athenaProjectID: ${athenaProjectID}
  athenaRegion: ${athenaRegion}
  athenaTable: ${athenaTable}
  projectID: ${projectID}
  spotLabel: eks.amazonaws.com/capacityType
  spotLabelValue: SPOT
kubecostToken: ${kubecostToken}
service:
  annotations: {}
  labels: {}
  port: 9090
  sessionAffinity:
    enabled: false # Makes sure that connections from a client are passed to the same Pod each time, when set to `true`. You should set it when you enabled authentication through OIDC or SAML integration.
    timeoutSeconds: 10800
  targetPort: 9090
  type: LoadBalancer
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${iam-role-arn}
  create: true
  name: ${service-account}
