repos:
  - hooks:
      - args:
          - --exclude
          - ADOPTERS.md
          - --exclude
          - .pre-commit-config.yaml
          - --exclude
          - .gitignore
          - --exclude
          - '*.drawio'
          - --exclude
          - mkdocs.yml
          - --exclude
          - .helmignore
          - --exclude
          - .github/workflows/*
          - --exclude
          - patterns/istio-multi-cluster/*
          - --exclude
          - patterns/blue-green-upgrade/*
          - --exclude
          - /patterns/vpc-lattice/cross-cluster-pod-communication/*
          - --exclude
          - patterns/bottlerocket/*
          - --exclude
          - patterns/nvidia-gpu-efa/generate-efa-nccl-test.sh
        id: cspell
    repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.0.1
  - hooks:
      - args:
          - --autofix
          - --indent
          - "2"
          - --offset
          - "2"
          - --preserve-quotes
        id: pretty-format-yaml
    repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - args:
          - --allow-missing-credentials
        id: detect-aws-credentials
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - id: terraform_fmt
      - args:
          - --args=--lockfile=false
        id: terraform_docs
      - args:
          - --args=--only=terraform_deprecated_interpolation
          - --args=--only=terraform_deprecated_index
          - --args=--only=terraform_unused_declarations
          - --args=--only=terraform_comment_syntax
          - --args=--only=terraform_documented_outputs
          - --args=--only=terraform_documented_variables
          - --args=--only=terraform_typed_variables
          - --args=--only=terraform_module_pinned_source
          - --args=--only=terraform_naming_convention
          - --args=--only=terraform_required_version
          - --args=--only=terraform_required_providers
          - --args=--only=terraform_unused_required_providers
          - --args=--only=terraform_workspace_remote
        id: terraform_tflint
      - exclude: (docs|modules)
        id: terraform_validate
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
