copyright: Copyright &copy; Amazon 2024
docs_dir: docs/
extra:
  version:
    provider: mike
hooks:
  - .github/scripts/mkdocs-hooks.py
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - include-markdown
  - search:
      lang:
        - en
  - awesome-pages
repo_name: terraform-aws-eks-blueprints
repo_url: https://github.com/aws-ia/terraform-aws-eks-blueprints
site_author: AWS
site_name: Amazon EKS Blueprints for Terraform
site_url: https://aws-ia.github.io/terraform-aws-eks-blueprints/
theme:
  favicon: images/colored-logo.png
  features:
    - navigation.tabs.sticky
  font:
    text: ember
  highlightjs: true
  hljs_languages:
    - yaml
    - json
  icon:
    admonition:
      abstract: octicons/checklist-16
      bug: octicons/bug-16
      danger: octicons/zap-16
      example: octicons/beaker-16
      failure: octicons/x-circle-16
      info: octicons/info-16
      note: octicons/tag-16
      question: octicons/question-16
      quote: octicons/quote-16
      success: octicons/check-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
    repo: fontawesome/brands/github
  logo: images/white-logo.png
  name: material
  palette:
    accent: orange
    primary: orange
