ec2nodeclass:
  blockDeviceMappings:
    ebs:
      kmsKeyID: ""
  role: ""
  securityGroupSelectorTerms:
    tags:
      karpenter.sh/discovery: ""
  subnetSelectorTerms:
    tags:
      karpenter.sh/discovery: ""
  tags:
    karpenter.sh/discovery: ""
nodepool:
  zone: []
