agones:
  allocator:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
  crds:
    cleanupOnDelete: true
  featureGates: ""
  image:
    controller:
      pullPolicy: IfNotPresent
    registry: us-docker.pkg.dev/agones-images/release
    sdk:
      alwaysPull: false
  ping:
    http:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
      serviceType: LoadBalancer
    udp:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
      expose: ${expose_udp}
      serviceType: LoadBalancer
gameservers:
  maxPort: ${gameserver_maxport}
  minPort: ${gameserver_minport}
  namespaces:
    - default
  podPreserveUnknownFields: false
