apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: client
spec:
  replicas: 1
  selector:
    matchLabels:
      role: client
  template:
    metadata:
      labels:
        role: client
    spec:
      containers:
        - command:
            - probe
            - --urls=http://frontend.stars:80/status,http://backend.stars:6379/status
          image: calico/star-probe:v0.1.0
          imagePullPolicy: Always
          name: client
          ports:
            - containerPort: 9000
