apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-ui
  namespace: management-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      role: management-ui
  template:
    metadata:
      labels:
        role: management-ui
    spec:
      containers:
        - image: calico/star-collect:v0.1.0
          imagePullPolicy: Always
          name: management-ui
          ports:
            - containerPort: 9001
